[package]
name = "multipoly"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2-base.workspace=true
num-traits.workspace = true
derivative.workspace = true
rand.workspace = true
